### ISSUE TITLE
Fix Travis CI build and codecov status badges

### ISSUE THREAD

**Issue by peter279k** [Lucky-Loek/Really-Simple-Http-Requests#2]
As title, it seems that the Travis CI build and codecov statuses are unknown.

@Lucky-Loek , please concern this issue and fix this at your available time.

Thanks.

**Comment by Lucky-Loek** [comment]
I've opted out of CodeCov a while ago, so removed that badge. Travis is updated now, also included test with PHP 7.3

Thanks!

**Comment by peter279k** [comment]
@Lucky-Loek, thanks for your concern!
